### ISSUE TITLE
Migrate Afterglow issues to Alpenglow

### ISSUE THREAD

**Issue by egeerardyn** [AlpenglowTheme/alpenglow-theme#27]
In the Afterglow repository, there are quite a few open issues and PRs.
We should make sure that we incorporate the relevant ones in our repository.

For convenience, I have made a TODO list here with the data from the GitHub API.
Checked items do not need further action (i.e. are migrated already, are not relevant here, ...). For most I have provided a reason.
## Already migrated

Issues/PRs that already have their own issue report here.

| Status | Issue here | Reference in Afterglow | Description |
| :-: | --- | --- | --- |
|  | **#17** | [IR17](https://github.com/YabataDesign/afterglow-theme/issues/108) and [IR17](https://github.com/YabataDesign/afterglow-theme/issues/108) | Light Theme? |
| ✅ | **#18** | [PR121](https://github.com/YabataDesign/afterglow-theme/pull/121) | Gitgutter support? |
|  | **#24** | [IR127](https://github.com/YabataDesign/afterglow-theme/issues/127) and [IR128](https://github.com/YabataDesign/afterglow-theme/issues/128) | Port to other editors? |
## Pull Requests
- [ ] [PR118 Add support for gulpfile.babel.js](https://github.com/YabataDesign/afterglow-theme/pull/118)
- [x] [PR113 Add MATLAB icon](https://github.com/YabataDesign/afterglow-theme/pull/113) done in 31bd0373cde4b6a4dc712eae0c3d4b8e4b847630 
- [ ] [PR111 Added icons for Haxe and Maxscript](https://github.com/YabataDesign/afterglow-theme/pull/111)
- [x] [PR110 Add icons for Julia, R, and Stata.](https://github.com/YabataDesign/afterglow-theme/pull/110) done in 0be8f5899a7f315bf5a621857dfb39a47ac0a195
- [ ] [PR106 Added statusbar font size option](https://github.com/YabataDesign/afterglow-theme/pull/106), [IR55 Change status bar font size](https://github.com/YabataDesign/afterglow-theme/issues/55), and [IR93 Possible to define font-size on status bar?](https://github.com/YabataDesign/afterglow-theme/issues/93)
- [ ] [PR104 Added plus-versions of themes with active color, active & modified color and inactive & modified color](https://github.com/YabataDesign/afterglow-theme/pull/104)
- [x] [PR95 fix Gulp and Grunt commenting and snippets, issue #72](https://github.com/YabataDesign/afterglow-theme/pull/95) done in 9f83ec59f5482b1775f6e4746fe58557cb18d630
- [x] [PR91 Give .gitmodules file a git icon](https://github.com/YabataDesign/afterglow-theme/pull/91) done in 006b9d8a3bfdf21206a5a2c680a353e17517c448
- [ ] [PR81 Sass icon for .scss & .sass files](https://github.com/YabataDesign/afterglow-theme/pull/81) and [IR80 Add separate icon for .scss & .sass files](https://github.com/YabataDesign/afterglow-theme/issues/80)
- [ ] [PR69 Add Laravel Blade icons](https://github.com/YabataDesign/afterglow-theme/pull/69) and [IR99 adding a laravel blade icon](https://github.com/YabataDesign/afterglow-theme/issues/99)
- [x] [PR35 Update readme](https://github.com/YabataDesign/afterglow-theme/pull/35) - Not relevant: tiny changes to README
- [x] [PR30 Revise copy text in index.html](https://github.com/YabataDesign/afterglow-theme/pull/30) - Not relevant: changes to website
## Issue Reports
- [x] [IR129 Ruby File icons not showing](https://github.com/YabataDesign/afterglow-theme/issues/129) see https://github.com/AlpenglowTheme/alpenglow-theme/issues/27#issuecomment-220236365
- [x] [IR126 incorrect PHP icon shown](https://github.com/YabataDesign/afterglow-theme/issues/126) done in https://github.com/AlpenglowTheme/alpenglow-theme/commit/d416f823460fa9c6621f2defb93e76a7965116ba and https://github.com/AlpenglowTheme/alpenglow-theme/issues/27#issuecomment-220236365
- [ ] [IR123 Windows 7 x64 not icons](https://github.com/YabataDesign/afterglow-theme/issues/123)
- [ ] [IR122 Theme colorscheme update needed after 3103](https://github.com/YabataDesign/afterglow-theme/issues/122)
- [x] [IR120 Is this being maintained?](https://github.com/YabataDesign/afterglow-theme/issues/120) This repository is maintained.
- [x] [IR119 Update link to replacement icon](https://github.com/YabataDesign/afterglow-theme/issues/119) done in 312500ceeb495bbecde42e3074d5023ab672ce6a
- [ ] [IR117 Files Tab bottom padding is the same color as the file background](https://github.com/YabataDesign/afterglow-theme/issues/117)
- [ ] [IR116 No SCSS/CSS Sidebar Icons](https://github.com/YabataDesign/afterglow-theme/issues/116)
- [x] [IR115 Problems with custom file types](https://github.com/YabataDesign/afterglow-theme/issues/115) done in 9f83ec59f5482b1775f6e4746fe58557cb18d630
- [ ] [IR112 The Main Font Color of Editor (Bright White) Is A Little Bit Too Bright](https://github.com/YabataDesign/afterglow-theme/issues/112)
- [ ] [IR109 feature request: ability to configure the size of the command palette pane](https://github.com/YabataDesign/afterglow-theme/issues/109)
- [ ] [IR107 context word in Monokai syntax is not colorize](https://github.com/YabataDesign/afterglow-theme/issues/107)
- [ ] [IR102 [FeatureRequest] Active Tabs with border color](https://github.com/YabataDesign/afterglow-theme/issues/102)
- [ ] [IR101 Add sass, scss and typescript highlighting](https://github.com/YabataDesign/afterglow-theme/issues/101)
- [ ] [IR100 Consider JSON Scope Highlighting](https://github.com/YabataDesign/afterglow-theme/issues/100) and [IR41 JSON highlighting](https://github.com/YabataDesign/afterglow-theme/issues/41)
- [x] [IR98 Missing sidebar icons OS X 10.6.8 [x86]](https://github.com/YabataDesign/afterglow-theme/issues/98) already solved
- [ ] [IR94 High CPU usage due to last update](https://github.com/YabataDesign/afterglow-theme/issues/94)
- [ ] [IR92 Syntax highlighting is off for the first bullet/number, screenshot attached](https://github.com/YabataDesign/afterglow-theme/issues/92)
- [ ] [IR89 Disable close buttons on non-active tabs](https://github.com/YabataDesign/afterglow-theme/issues/89)
- [ ] [IR76 Active row highlighting](https://github.com/YabataDesign/afterglow-theme/issues/76)
- [ ] [IR74 Not Showing sidebar icons base on the latest update](https://github.com/YabataDesign/afterglow-theme/issues/74)
- [x] [IR72 Gruntfile JS filetype breaks default comment key binding](https://github.com/YabataDesign/afterglow-theme/issues/72) see 9f83ec59f5482b1775f6e4746fe58557cb18d630
- [ ] [IR70 How to edit mappings for the new sidebar file type icons](https://github.com/YabataDesign/afterglow-theme/issues/70)
- [ ] [IR66 Space Underneath Tabs Help Suggestions?](https://github.com/YabataDesign/afterglow-theme/issues/66)
- [x] [IR56 After update to 2.0.6 the icons for the "Default" theme are missing.](https://github.com/YabataDesign/afterglow-theme/issues/56) solved in https://github.com/YabataDesign/afterglow-theme/issues/56#issuecomment-93031764
- [ ] [IR44 Is possible to edit the caret background when in Vintage mode on Afterglow-Markdown?](https://github.com/YabataDesign/afterglow-theme/issues/44)
- [ ] [IR42 Console input box is barely distinguishable](https://github.com/YabataDesign/afterglow-theme/issues/42)
- [x] [IR40 Why I can't remove colorcoder?](https://github.com/YabataDesign/afterglow-theme/issues/40) not our problem (colorcode bug?)
- [ ] [IR39 Color Schemes Placed In Different Folder by Package Control](https://github.com/YabataDesign/afterglow-theme/issues/39)
- [ ] [IR29 Change color for sql files](https://github.com/YabataDesign/afterglow-theme/issues/29)
- [x] [IR26 does not show up in Package Control install list](https://github.com/YabataDesign/afterglow-theme/issues/26) Not relevant for us. Just see #3 here for our case.
- [ ] [IR25 Adjust tab font size](https://github.com/YabataDesign/afterglow-theme/issues/25)
- [ ] [IR24 Search & replace "replace" button is cut off fromt he bottom on Yosemite](https://github.com/YabataDesign/afterglow-theme/issues/24)

**Note:** feel free to edit/update this post when necessary!

**Comment by vikjam** [comment]
I think we're good on PHP and Ruby:

![screen shot 2016-05-19 at 2 08 00 am](https://cloud.githubusercontent.com/assets/1154799/15384215/c521b2be-1d66-11e6-9d47-1c10071c811a.png)

I think d416f82 fixed PHP. I hadn't noticed any need to do anything about Ruby.

**Comment by egeerardyn** [comment]
I suspect the Ruby issue might be related to the Rails/ERB one that is indeed solved.
